[master]
spark-master ansible_host=spark-master ansible_user=root ansible_connection=docker

[workers]
spark-worker-1 ansible_host=spark-worker-1 ansible_user=root ansible_connection=docker
spark-worker-2 ansible_host=spark-worker-2 ansible_user=root ansible_connection=docker

[spark:children]
master
workers
