import numpy as np


def generate_density(dim, random_state=None):
    """
    Create a mixture-based probability density function in arbitrary dimension.

    Parameters
    ----------
    dim : int
        Dimension of the space
    random_state : int or None
        Random seed

    Returns
    -------
    density : callable
        Function that evaluates the density at a point x
    """

    rng = np.random.default_rng(random_state)

    # scale factor to keep values within [-1, 1]
    scale = 0.7

    # random linear map that generates extra dimensions from the base 2D structure
    if dim > 2:
        R = rng.normal(size=(dim-2, 2))
    else:
        R = None

    means = []
    weights = []

    base_points = [
        (-0.4, 0.4),
        (0.4, 0.4)
    ]

    for p in base_points:
        x, y = p
        m = np.zeros(dim)
        m[0] = scale * x
        m[1] = scale * y

        if R is not None:
            m[2:] = scale * (R @ np.array([x, y]))

        means.append(m)
        weights.append(0.2)

    angles = np.linspace(-2.5, -0.6, 20)

    for a in angles:
        x = 0.8 * np.cos(a)
        y = 0.8 * np.sin(a) - 0.2
        m = np.zeros(dim)
        m[0] = scale * x
        m[1] = scale * y

        if R is not None:
            m[2:] = scale * (R @ np.array([x, y]))

        means.append(m)
        weights.append(0.05)

    weights = np.array(weights, dtype=float)
    means = np.array(means)
    weights = weights / weights.sum()
    K = len(means)

    # smaller variance so mixture components remain visually separated
    var_xy = 0.01

    cov_diag = np.full(dim, var_xy)

    norm_const = 1 / np.sqrt((2*np.pi)**dim * np.prod(cov_diag))
    inv_cov = 1 / cov_diag
    coeff = weights * norm_const

    cov_diag_sqrt = np.sqrt(cov_diag)

    def density(x):
        x = np.atleast_2d(x)

        diff = x[:, None, :] - means[None, :, :]
        exponent = -0.5 * np.sum(diff * diff * inv_cov, axis=2)

        values = np.sum(coeff * np.exp(exponent), axis=1)

        if values.shape[0] == 1:
            return values[0]
        return values

    density.means = means
    density.weights = weights
    density.cov_diag = cov_diag
    density.cov_diag_sqrt = cov_diag_sqrt

    return density


def sample_from_density(density, dim, n_samples, random_state=None):
    """
    Generate samples using rejection sampling.

    Parameters
    ----------
    density : callable
        Density function
    dim : int
        Dimension of the space
    n_samples : int
        Number of samples
    random_state : int or None
        Random seed

    Returns
    -------
    samples : ndarray (n_samples, dim)
    """

    rng = np.random.default_rng(random_state)

    # fast sampling if density was generated by generate_density
    if hasattr(density, "means"):
        means = density.means
        weights = density.weights
        scale = density.cov_diag_sqrt

        K, dim_check = means.shape
        assert dim_check == dim

        components = rng.choice(K, size=n_samples, p=weights)

        # vectorized sampling from the selected Gaussian components
        samples = rng.normal(size=(n_samples, dim)) * scale + means[components]

        return samples

    # fallback rejection sampling
    samples = []
    max_density = 1.0
    batch_size = 5000

    while len(samples) < n_samples:
        X = rng.uniform(-3, 3, size=(batch_size, dim))

        probs = np.array([density(x) for x in X])
        accept = rng.random(batch_size) < probs / max_density

        accepted = X[accept]

        for x in accepted:
            samples.append(x)
            if len(samples) >= n_samples:
                break

    return np.array(samples)